<a href="https://colab.research.google.com/github/pyonan/Creating-and-Uploading-Datasets/blob/main/experiment10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

data={
    'Roll_No':[1,2,3,4,5],
    'Gender':['F','M','F','M','F'],
    'Department':['ENTC','RA','Mech','AIML','CSE'],
    'CGPA':[9.6,9.5,8.4,8.5,7.6]
}

df=pd.DataFrame(data)

df.to_csv('student_database.csv',index=False)
df

   Roll_No Gender Department  CGPA
0        1      F       ENTC   9.6
1        2      M         RA   9.5
2        3      F       Mech   8.4
3        4      M       AIML   8.5
4        5      F        CSE   7.6

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll_No     5 non-null      int64
 1   Gender      5 non-null      object
 2   Department  5 non-null      object
 3   CGPA        5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [3]:
df.shape

(5, 4)

In [ ]:
#Access information about a column
df['Department']

0    ENTC
1      RA
2    Mech
3    AIML
4     CSE
Name: Department, dtype: object

In [ ]:
#Access information about a row
df.loc[2]

Roll_No          3
Gender           F
Department    Mech
CGPA           8.4
Name: 2, dtype: object

In [ ]:
#Data type of each column
df.dtypes

Roll_No         int64
Gender         object
Department     object
CGPA          float64
dtype: object

In [ ]:
#Perform mean, median, mode
mean=df['CGPA'].mean()
median=df['CGPA'].median()
mode=df['Department'].mode()

print(mean)
print(median)
print(mode)

8.72
8.5
0    AIML
1     CSE
2    ENTC
3    Mech
4      RA
Name: Department, dtype: object

In [ ]:
#Insert a new column
df['Grade']=[96,94,81,85,71]
df

   Roll_No Gender Department  CGPA  Grade
0        1      F       ENTC   9.6     96
1        2      M         RA   9.5     94
2        3      F       Mech   8.4     81
3        4      M       AIML   8.5     85
4        5      F        CSE   7.6     71

In [ ]:
#Delete a column
df.drop('Gender',axis=1,inplace=True)
df

   Roll_No Department  CGPA  Grade
0        1       ENTC   9.6     96
1        2         RA   9.5     94
2        3       Mech   8.4     81
3        4       AIML   8.5     85
4        5        CSE   7.6     71

In [4]:
#CGPA of Topper
df.loc[0,'CGPA']

np.float64(9.6)

In [ ]:
df.iloc[4,2]

np.float64(7.6)

### Load Dataset

In [17]:
from google.colab import files
uploaded = files.upload()
import pandas as pd
df=pd.read_csv('Cars93.csv')

Saving Cars93.csv to Cars93.csv

In [18]:
df.size

930

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [20]:
df.shape

(93, 10)

In [21]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [22]:
df.tail()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0